cuda_mppi_controller:
  ros__parameters:
    # --- Limits (User Provided) ---
    max_steer: 0.507        # rad (약 40도)
    min_accel: -9.0      # m/s^2
    max_accel: 9.0       # m/s^2
    min_speed: 0.0        # m/s
    target_speed: 5.0    # m/s
    max_speed: 10.0       # m/s
    
    # --- Costs ---
    q_dist: 1.0
    q_v: 2.0
    q_du: 1.0
    q_collision: 450.0
    collision_radius: 0.28
    
    # --- Noise & Tuning ---
    # 한번에 얼마까지 변화를 줄까
    noise_steer_std: 0.45  # rad/s
    noise_accel_std: 3.0  # m/s^2
    max_steer_rate: 4.0  # rad/s (약 229도/s)
    max_accel_rate: 1000.0   # m/s^3
    lambda: 15.0
    visualize_candidates: true
    
    # --- Dynamic Model Params ---
    mass: 3.5
    l_f: 0.17
    l_r: 0.17
    I_z: 0.07
    
    # Pacejka Coefficients
    B_f: 1.5
    C_f: 1.5
    D_f: 15.0
    
    B_r: 1.5
    C_r: 1.5
    D_r: 15.0
    
    odom_topic: /odom0
    scan_topic: /scan0
    drive_topic: /ackermann_cmd0
    path_topic: /center_path