mppi_controller:
  ros__parameters:
    max_steer: 0.52
    min_accel: -3.0
    max_accel: 3.0
    min_speed: 0.0
    target_speed: 3.0
    max_speed: 5.0
    q_dist: 10.0
    q_v: 5.0
    q_lat: 0.2
    q_u: 1.0
    q_du: 3.0
    collision_radius: 0.30
    odom_topic: /odom0
    scan_topic: /scan0
    drive_topic: /ackermann_cmd0
    path_topic: /center_path
