/**:
  ros__parameters:
    # --- Limits ---
    max_steer: 0.4089        # rad
    min_accel: -9.0         # m/s^2
    max_accel: 9.0          # m/s^2
    min_speed: 0.0          # m/s
    target_speed: 6.5       # m/s
    max_speed: 6.5         # m/s
    
    # --- Path Publisher Params (곡률 감속용) ---
    max_lat_g: 9.0         # 최대 횡가속도 한계 (m/s^2)
    max_decel: 9.0          # 코너 진입 전 브레이킹 한계 감속도
    
    # --- Costs (공통 기본값) ---
    q_v: 1.3
    q_dist: 0.0 
    q_du: 0.2
    q_steer: 3.0
    q_collision: 150.0
    q_lat_g: 250.0
    collision_radius: 0.21
    q_progress: 16.0
    q_escape_vel: 6.5
    
    # --- Obstacle Avoidance Params ---
    car_radius: 0.15
    q_obs: 50.0
    
    # --- Noise & Tuning ---
    noise_steer_std: 0.4    # rad/s
    noise_accel_std: 2.0    # m/s^3
    max_steer_rate: 8.0     # rad/s
    max_accel_rate: 100.0  # m/s^3
    lambda: 15.0
    visualize_candidates: true
    
    # --- Dynamic Model Params ---
    mass: 3.74
    l_f: 0.163
    l_r: 0.162
    I_z: 0.04712
    
    # Pacejka Coefficients
    B_f: 1.7
    C_f: 1.5
    D_f: 40.0
    
    B_r: 1.7
    C_r: 1.5
    D_r: 40.0

    # --- Topics (공통 키) ---
    odom_topic: /odom0
    pose_topic: /mcl_pose
    velocity_topic: /odom
    drive_topic: /ackermann_cmd0
    path_topic: /mppi_target_path
    use_mcl_pose: false